In [309]:
import pandas as pd, numpy as np

In [310]:
train = pd.read_csv(r'C:\Users\Anjana Tiha\OneDrive - The University of Memphis\Programming\data\iris\iris.csv')

In [311]:
feature_cols = ['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']
target_col = 'Species'

features = train[feature_cols]
target = train[target_col]

features.describe()
target.describe()

X = features.values
Y= target


In [312]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(Y)
Y=le.transform(Y)
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [313]:
# from sklearn.preprocessing import OneHotEncoder
# enc = OneHotEncoder()
# enc.fit(Y)  
# Y=enc.transform(Y).toarray()
# Y

In [314]:
from sklearn import linear_model
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import StratifiedShuffleSplit


from sklearn import metrics

logreg = linear_model.LogisticRegression()
neigh = KNeighborsClassifier(n_neighbors=3)

sss = StratifiedShuffleSplit(n_splits=5, test_size=0.5, random_state=0)
sss.get_n_splits(X, Y)      
i=0
for train_index, test_index in sss.split(X, Y):
    print("***************************************", "StratifiedShuffleSplitFold", i+1, "*******************************")
#     print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
#     logreg.fit(X_train, y_train)
#     predict = logreg.predict(X_test)
    neigh.fit(X_train, y_train) 
    predict = neigh.predict(X_test)
    print("\n")
    print("accuracy_score", metrics.accuracy_score(y_test, predict))
    print("precision_score", metrics.precision_score(y_test, predict, average="micro"))
    print("recall_score", metrics.recall_score(y_test, predict, average="micro"))
    print("f1_score", metrics.f1_score(y_test, predict, average="micro"))
    print("hamming_loss", metrics.hamming_loss(y_test, predict))
#     precision, recall, thresholds = metrics.precision_recall_curve(y_test, predict)
#     print("average_precision_score", metrics.average_precision_score(y_test, predict, average="micro"))
#     print("fbeta_score", metrics.fbeta_score(y_test, predict))
#     print("roc_auc_score", metrics.roc_auc_score(y_test, predict, average="micro"))
    print("\n")
    print("------------------------------------------------")
    print(metrics.classification_report(y_test, predict))
    print("------------------------------------------------")
    print("confusion_matrix\n\n", metrics.confusion_matrix(y_test, predict))
    print("\n")
    i+=1
    

*************************************** StratifiedShuffleSplitFold 1 *******************************


accuracy_score 0.9733333333333334
precision_score 0.9733333333333334
recall_score 0.9733333333333334
f1_score 0.9733333333333334
hamming_loss 0.02666666666666667


------------------------------------------------
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        25
          1       0.96      0.96      0.96        25
          2       0.96      0.96      0.96        25

avg / total       0.97      0.97      0.97        75

------------------------------------------------
confusion_matrix

 [[25  0  0]
 [ 0 24  1]
 [ 0  1 24]]


*************************************** StratifiedShuffleSplitFold 2 *******************************


accuracy_score 0.96
precision_score 0.96
recall_score 0.96
f1_score 0.96
hamming_loss 0.04


------------------------------------------------
             precision    recall  f1-score   support

          

In [307]:
# %config IPCompleter.greedy=True